"""Initial migration

Revision ID: 56262ecc232d
Revises: 
Create Date: 2025-08-22 16:25:03.251913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56262ecc232d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('patient_phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_email', sa.String(length=120), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('patient_email')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('patient_phone')
        batch_op.drop_column('patient_email')

    # ### end Alembic commands ###
